SELECT 
	IDT_TRANSACTION,
	IDT_CONTA,DTA_TRANSACAO,
	VLR_TRANSACAO,
	DTA_AGENDAMENTO,
	BANCO_CONTRAPARTE,
	AGENCIA_CONTRAPARTE,
	CONTA_CONTRAPARTE,
	DOCUMENTO_CONTRAPARTE 
FROM 
	TB_TRANSACAO 
WHERE 
	CONVERT(nvarchar(max), ISNULL(IDT_TRANSACTION, '')) COLLATE DATABASE_DEFAULT + 
	CONVERT(nvarchar(max), ISNULL(IDT_CONTA, '')) COLLATE DATABASE_DEFAULT + 
	CONVERT(nvarchar(max), ISNULL(DTA_TRANSACAO, '')) COLLATE DATABASE_DEFAULT + 
	CONVERT(nvarchar(max), ISNULL(VLR_TRANSACAO, '')) COLLATE DATABASE_DEFAULT + 
	CONVERT(nvarchar(max), ISNULL(DTA_AGENDAMENTO, '')) COLLATE DATABASE_DEFAULT + 
	CONVERT(nvarchar(max), ISNULL(BANCO_CONTRAPARTE, '')) COLLATE DATABASE_DEFAULT + 
	CONVERT(nvarchar(max), ISNULL(AGENCIA_CONTRAPARTE, '')) COLLATE DATABASE_DEFAULT + 
	CONVERT(nvarchar(max), ISNULL(CONTA_CONTRAPARTE, '')) COLLATE DATABASE_DEFAULT + 
	CONVERT(nvarchar(max), ISNULL(DOCUMENTO_CONTRAPARTE, '')) COLLATE DATABASE_DEFAULT LIKE '%327%' 
--AND IDT_TRANSACTION = 701
ORDER BY 
	DTA_TRANSACAO DESC 
OFFSET 0 ROWS 
FETCH NEXT 8 ROWS ONLY
--701

DECLARE @table nvarchar(256) = 'TB_TRANSACAO';
DECLARE @stringToFind AS varchar(255) = '327'

   DECLARE @sqlCommand varchar(max) = 'SELECT * FROM ' + @table + ' WHERE ' 
	   
   SELECT @sqlCommand = @sqlCommand + '[' + COLUMN_NAME + '] LIKE ''' + @stringToFind + ''' OR '
   FROM INFORMATION_SCHEMA.COLUMNS 
   WHERE TABLE_SCHEMA = 'dbo'
   AND TABLE_NAME = @table 
   AND DATA_TYPE IN ('char','nchar','ntext','nvarchar','text','varchar')

   SET @sqlCommand = left(@sqlCommand,len(@sqlCommand)-3)
--   EXEC (@sqlCommand)
   PRINT @sqlCommand

